import fs from 'node:fs';import path from 'node:path';import { randomUUID } from 'node:crypto';import type {AfkRecord,AuditLog,NavCategory,Task,User} from './types';import type {PermissionMap} from './permissions';import {ROLE_PERMISSIONS} from './permissions';

type DB={users:User[];nav:NavCategory[];tasks:Task[];afk:AfkRecord[];audit:AuditLog[];rolePermissions:PermissionMap};
const file=path.join(process.cwd(),'data','db.json');
const seed=():DB=>{const admin:User={id:'u-admin',telegramId:10001,username:'demo_admin',firstName:'Demo',lastName:'Admin',stars:5,role:'SUPER_ADMIN'};const senior:User={id:'u-senior',telegramId:10002,username:'senior_admin',firstName:'Senior',lastName:'Admin',stars:4,role:'SENIOR_ADMIN'};const user:User={id:'u-user',telegramId:10003,username:'demo_user',firstName:'Demo',lastName:'User',stars:3,role:'SENIOR_STAFF'};const now=new Date().toISOString();return{users:[admin,senior,user],nav:[{id:'cat-main',title:'Основное',icon:'◈',items:[{id:'nav-rules',title:'Правила',body:'Основные правила команды, стандарты поведения и порядок взаимодействия.'},{id:'nav-contacts',title:'Контакты',body:'Контакты руководства и полезные ссылки.'}]},{id:'cat-learn',title:'Обучение',icon:'⌘',items:[{id:'nav-training',title:'Базовое обучение',body:'Материалы для новых сотрудников.'},{id:'nav-checks',title:'Проверки',body:'Порядок проведения проверок и оформления результатов.'}]},{id:'cat-tools',title:'Инструменты',icon:'◎',items:[{id:'nav-tools',title:'Рабочие инструменты',body:'Список инструментов и инструкции по их использованию.'}]}],tasks:[{id:'task-1',title:'Проверить раздел «Правила»',description:'Проверить актуальность текста и сообщить об изменениях.',status:'NEW',priority:'HIGH',assigneeId:user.id,createdBy:admin.id,createdAt:now},{id:'task-2',title:'Обновить обучающий материал',description:'Добавить примеры в базовый материал.',status:'IN_PROGRESS',priority:'MEDIUM',assigneeId:user.id,createdBy:senior.id,createdAt:now},{id:'task-3',title:'Проверить AFK-реестр',description:'Проверить активные записи AFK.',status:'DONE',priority:'LOW',createdBy:admin.id,createdAt:now}],afk:[],audit:[{id:randomUUID(),actorId:admin.id,action:'SEED','entity':'SYSTEM',createdAt:now}],rolePermissions:JSON.parse(JSON.stringify(ROLE_PERMISSIONS))}};
function read():DB{try{if(!fs.existsSync(file)){const d=seed();if(process.env.NODE_ENV!=='production' || process.env.DEMO_MODE==='true'){fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,JSON.stringify(d,null,2));}return d}return JSON.parse(fs.readFileSync(file,'utf8'))}catch{return seed()}}
function write(d:DB){if(process.env.NODE_ENV==='production')return;fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,JSON.stringify(d,null,2))}
export function db(){return read()}
export function updateDB(fn:(d:DB)=>void){const d=read();fn(d);write(d);return d}
export function uid(){return randomUUID()}
export function audit(actorId:string,action:string,entity:string,entityId?:string,payload?:Record<string,unknown>){updateDB(d=>d.audit.unshift({id:uid(),actorId,action,entity,entityId,payload,createdAt:new Date().toISOString()}))}
